# Generated by Django 3.2 on 2021-05-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='sub1',
        ),
        migrations.AddField(
            model_name='subject',
            name='sub2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub5',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub6',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub7',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub8',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
