# Generated by Django 3.2 on 2021-05-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentInfo', '0002_auto_20210503_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sub1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub5',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub6',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub7',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub8',
        ),
    ]
