# Generated by Django 3.2 on 2021-05-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentInfo', '0003_auto_20210503_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='sub_name',
        ),
    ]
