# Generated by Django 3.2 on 2021-05-03 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentInfo', '0004_rename_name_subject_sub_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Inter',
        ),
        migrations.RenameField(
            model_name='inter',
            old_name='marks',
            new_name='inter_marks',
        ),
        migrations.RenameField(
            model_name='inter',
            old_name='sub_name',
            new_name='inter_sub_name',
        ),
        migrations.CreateModel(
            name='Tenth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_sub_name', models.CharField(blank=True, max_length=40)),
                ('marks', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_sub_name', models.CharField(blank=True, max_length=40)),
                ('engineer_marks', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
