# Generated by Django 3.2 on 2021-05-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentInfo', '0005_auto_20210503_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenth',
            old_name='marks',
            new_name='tenth_marks',
        ),
    ]
